name: Urus CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential gcc

    - name: Configure CMake
      run: cmake -S compiler -B compiler/build -DCMAKE_BUILD_TYPE=Release

    - name: Build Urus Compiler
      run: cmake --build compiler/build --parallel $(nproc)

    - name: Install stdlib
      run: |
        sudo mkdir -p /usr/lib/urusc
        sudo cp compiler/stdlib/*.urus /usr/lib/urusc/

    - name: Run CTest
      run: ctest --test-dir compiler/build --output-on-failure --parallel $(nproc)
